const products = [
  {
    id: 1001,
    title: "Carnival Pack Assortment (S & S)",
    stock: true,
    category: "Assortment",
    brand: "Sky Pioneer",
    package: [36, 1],
    price: 229.99,
    effects: "strobes, crackles, sizzles, snaps, loud bangs, fan effects, willows,",
    colors: "green, red, blue, purple, pink, white",
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1001.png"
  },
  {
    id: 1023,
    title: "Wise Guy Assortment Box",
    stock: true,
    category: "Assortment",
    brand: "Wise Guy",
    package: [4, 1],
    price: 299.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1023.jpeg"
  },
  {
    id: 1041,
    title: "Container Load Blue",
    stock: true,
    category: "Assortment",
    brand: "Winda",
    package: [1, 4],
    price: 239.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1041.png"
  },
  {
    id: 1046,
    title: "Aces High",
    stock: true,
    category: "Assortment",
    brand: "Miracle",
    package: [6, 1],
    price: 279.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1046.jpeg"
  },
  {
    id: 1053,
    title: "Private Pirate",
    stock: true,
    category: "Assortment",
    brand: "STARGET",
    package: [1, 10],
    price: 279.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1053.png"
  },
  {
    id: 1056,
    title: "Gorgeous Assortment",
    stock: true,
    category: "Assortment",
    brand: "Legend",
    package: [6, 1],
    price: 329.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1056.jpeg"
  },
  {
    id: 1058,
    title: "Ecstatic Assortment",
    stock: true,
    category: "Assortment",
    brand: "Legend",
    package: [6, 1],
    price: 249.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1058.jpeg"
  },
  {
    id: 1063,
    title: "Moon Assortment (S & S)",
    stock: true,
    category: "Assortment",
    brand: "Legend",
    package: [12, 1],
    price: 349.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1063.png"
  },
  {
    id: 1064,
    title: "Sky Thunder Assortment",
    stock: true,
    category: "Assortment",
    brand: "Shogun",
    package: [2, 1],
    price: 289.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1064.png"
  },
  {
    id: 1065,
    title: "Fireworks Star Assortment",
    stock: true,
    category: "Assortment",
    brand: "Shogun",
    package: [6, 1],
    price: 289.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1065.png"
  },
  {
    id: 1071,
    title: "Treasure Island",
    stock: true,
    category: "Assortment",
    brand: "StarGet",
    package: [1, 15],
    price: 399.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1071.png"
  },
  {
    id: 1076,
    title: "Alien Party (S & S)",
    stock: true,
    category: "Assortment",
    brand: "TopGun",
    package: [8, 1],
    price: 239.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1076.jpeg"
  },
  {
    id: 1078,
    title: "Diamond Series Fountain Assortment (S & S)",
    stock: true,
    category: "Assortment",
    brand: "TopGun",
    package: [4, 1],
    price: 169.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1078.jpeg"
  },
  {
    id: 1080,
    title: "Mammoth Assortment",
    stock: true,
    category: "Assortment",
    brand: "StarGet",
    package: [2, 1],
    price: 169.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1080.jpeg"
  },
  {
    id: 1081,
    title: "Munition Store",
    stock: true,
    category: "Assortment",
    brand: "Shogun",
    package: [2, 1],
    price: 369.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1081.png"
  },
  {
    id: 1084,
    title: "Fireworks Sun Assortment",
    stock: true,
    category: "Assortment",
    brand: "Shogun",
    package: [8, 1],
    price: 289.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1084.png"
  },
  {
    id: 1104,
    title: "Aerial Party",
    stock: true,
    category: "Assortment",
    brand: "Shogun",
    package: [2, 1],
    price: 229.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1105,
    title: "Whale Assortment",
    stock: true,
    category: "Assortment",
    brand: "Pyro Mooi",
    package: [4, 1],
    price: 279.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1105.png"
  },
  {
    id: 1107,
    title: "Power Play Assortment",
    stock: true,
    category: "Assortment",
    brand: "Hop Kee",
    package: [6, 1],
    price: 239.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1107.jpeg"
  },
  {
    id: 1109,
    title: "Pinnacle Assortment",
    stock: true,
    category: "Assortment",
    brand: "Brothers",
    package: [6, 1],
    price: 399.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1109.webp"
  },
  {
    id: 1111,
    title: "American #1",
    stock: true,
    category: "Assortment",
    brand: "Wise Guy",
    package: [4, 1],
    price: 329.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1113,
    title: "King of Pyro",
    stock: true,
    category: "Assortment",
    brand: "Wise Guy",
    package: [3, 1],
    price: 339.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1113.png"
  },
  {
    id: 1114,
    title: "Battle for Freedom",
    stock: true,
    category: "Assortment",
    brand: "Sky Pioneer",
    package: [6, 1],
    price: 309.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1117,
    title: "Kid Party (S & S)",
    stock: true,
    category: "Assortment",
    brand: "Sky Pioneer",
    package: [24, 1],
    price: 219.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1117.jpeg"
  },
  {
    id: 1118,
    title: "Let Freedom Ring(S & S)",
    stock: true,
    category: "Assortment",
    brand: "Sky Pioneer",
    package: [9, 1],
    price: 249.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1121,
    title: "Blade Crush",
    stock: true,
    category: "Assortment",
    brand: "Sky Pioneer",
    package: [2, 1],
    price: 219.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1122,
    title: "Independence Day 1776 (S & S)",
    stock: true,
    category: "Assortment",
    brand: "Sky Pioneer",
    package: [12, 1],
    price: 329.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1122.png"
  },
  {
    id: 1125,
    title: "Kids Backpack",
    stock: true,
    category: "Assortment",
    brand: "Wise Guy",
    package: [12, 1],
    price: 329.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1125.png"
  },
  {
    id: 1126,
    title: "Life Of The Party",
    stock: true,
    category: "Assortment",
    brand: "Winda",
    package: [1, 1],
    price: 189.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1126.jpeg"
  },
  {
    id: 1128,
    title: "Air Force",
    stock: true,
    category: "Assortment",
    brand: "Red Lantern",
    package: [1, 1],
    price: 299.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1129,
    title: "American Proud",
    stock: true,
    category: "Assortment",
    brand: "Red Lantern",
    package: [4, 1],
    price: 269.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1129.jpeg"
  },
  {
    id: 1130,
    title: "All For One",
    stock: true,
    category: "Assortment",
    brand: "Red Lantern",
    package: [2, 1],
    price: 319.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1130.jpeg"
  },
  {
    id: 1131,
    title: "Hero Landing",
    stock: true,
    category: "Assortment",
    brand: "Red Lantern",
    package: [4, 1],
    price: 429.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1131.jpeg"
  },
  {
    id: 1137,
    title: "Lightning Storm",
    stock: true,
    category: "Assortment",
    brand: "Black Scorpion",
    package: [5, 1],
    price: 189.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1137.webp"
  },
  {
    id: 1138,
    title: "Need For Speed",
    stock: true,
    category: "Assortment",
    brand: "Black Scorpion",
    package: [6, 1],
    price: 299.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1138.webp"
  },
  {
    id: 1139,
    title: "Shark Zone",
    stock: true,
    category: "Assortment",
    brand: "Black Scorpion",
    package: [3, 1],
    price: 359.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1139.webp"
  },
  {
    id: 1140,
    title: "Fat Pack",
    stock: true,
    category: "Assortment",
    brand: "MC Fireworks",
    package: [3, 1],
    price: 159.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1142,
    title: "Big Buddha",
    stock: true,
    category: "Assortment",
    brand: "Pyro Mooi",
    package: [1, 16],
    price: 569.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-1142.jpeg"
  },
  {
    id: 1143,
    title: "Haste Hawk Car Assortment",
    stock: true,
    category: "Assortment",
    brand: "Pyro Mooi",
    package: [8, 1],
    price: 119.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1144,
    title: "Backyard Party",
    stock: true,
    category: "Assortment",
    brand: "Happy Family",
    package: [2, 1],
    price: 199.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1145,
    title: "Ball Of Fun Assortment",
    stock: true,
    category: "Assortment",
    brand: "Dominator",
    package: [2, 24],
    price: 369.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1146,
    title: "Boom Ball",
    stock: true,
    category: "Assortment",
    brand: "Dominator",
    package: [4, 36],
    price: 339.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1147,
    title: "Monstrous Assortment",
    stock: true,
    category: "Assortment",
    brand: "Dominator",
    package: [1, 1],
    price: 259.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 1148,
    title: "Monstrous Assortment",
    stock: true,
    category: "Assortment",
    brand: "Sky Pioneer",
    package: [1, 1],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 2004,
    title: "M-500 Brand",
    stock: true,
    category: "Firecrackers",
    brand: "Sky Pioneer",
    package: [40, 36],
    price: 109.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 2008,
    title: "Wise Guy Firecrackers 12/80/16",
    stock: true,
    category: "Firecrackers",
    brand: "Wise Guy",
    package: [12, 80, 16],
    price: 109.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2008.jpeg"
  },
  {
    id: 2010,
    title: "Wise Guy Firecrackers 8/10/200",
    stock: true,
    category: "Firecrackers",
    brand: "Wise Guy",
    package: [8, 10, 200],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2010.jpeg"
  },
  {
    id: 2011,
    title: "Wise Guy Firecrackers 24/40/16",
    stock: true,
    category: "Firecrackers",
    brand: "Wise Guy",
    package: [24, 40, 16],
    price: 109.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2011.jpeg"
  },
  {
    id: 2066,
    title: "Muscle Pack",
    stock: true,
    category: "Firecrackers",
    brand: "Winda",
    package: [100, 100],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2066.png"
  },
  {
    id: 2074,
    title: "Lightning Firecracker 4/4000",
    stock: true,
    category: "Firecrackers",
    brand: "Red Lantern",
    package: [4, 4000],
    price: 89.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2074.png"
  },
  {
    id: 2075,
    title: "Lightning Firecracker 2/8000",
    stock: true,
    category: "Firecrackers",
    brand: "Sky Pioneer",
    package: [2, 8000],
    price: 89.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2075.jpeg"
  },
  {
    id: 2077,
    title: "La Maxi Petarade Demon 400",
    stock: true,
    category: "Firecrackers",
    brand: "Black Scorpion",
    package: [4, 10, 400],
    price: 99.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2077.jpeg"
  },
  {
    id: 2083,
    title: "Firecrackers Boomers//Mighty Max 12/80/16",
    stock: true,
    category: "Firecrackers",
    brand: "Hop Kee",
    package: [12, 80, 16],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2083.png"
  },
  {
    id: 2085,
    title: "Thunder Bomb Firecrackers 32/40/12",
    stock: true,
    category: "Firecrackers",
    brand: "Sky Pioneer",
    package: [32, 40, 12],
    price: 109.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-2085.jpeg"
  },
  {
    id: 2094,
    title: "Lightning Firecracker 800 Rolls",
    stock: true,
    category: "Firecrackers",
    brand: "Red Lantern",
    package: [20, 800],
    price: 109.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 2096,
    title: "Gorilla Firecracker",
    stock: true,
    category: "Firecrackers",
    brand: "Legend",
    package: [24, 40, 16],
    price: 119.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 2099,
    title: "Black Label 1 Inch",
    stock: true,
    category: "Firecrackers",
    brand: "Dominator",
    package: [100, 100],
    price: 119.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {
    id: 3000,
    title: "Jumbo Smoke Balls (8/12/3)",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Sky Pioneer",
    package: [8, 12, 3],
    price: 139.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 3002,
    title: "Black Snakes/Color Snakes",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Legend",
    package: [15, 48, 6],
    price: 159.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3002.jpeg"
  },
  {  id: 3004,
    title: "Color Smoke Balls (20/12/6)",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Miracle",
    package: [20, 12, 6],
    price: 159.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3004.jpeg"
  },
  {  id: 3015,
    title: "Pink Lady",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Hop Kee",
    package: [72, 2],
    price: 179.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3015.jpeg"
  },
  {  id: 3034,
    title: "Large Painted Giant Smoke Balls",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Black Scorpion",
    package: [2, 12],
    price: 109.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3034.png"
  },
  {  id: 3037,
    title: "Smoke Grenade (Pull String)",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Sky Pioneer",
    package: [6, 24],
    price: 149.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 3038,
    title: "Mammoth White Smoke 5 Minutes",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Topgun",
    package: [100, 1],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3038.webp"
  },
  {  id: 3038,
    title: "Color Smoke Balls (Clay)",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Topgun",
    package: [20, 6, 12],
    price: 219.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 3041,
    title: "Snake Pit (Assorted Snakes)",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Sky Pioneer",
    package: [24, 12],
    price: 159.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3041.jpeg"
  },
  {  id: 3042,
    title: "Black Smoke",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Topgun",
    package: [6, 12],
    price: 169.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3042.png"
  },
  {  id: 3048,
    title: "USA Patriot Smoke Red White Blue",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Sky Pioneer",
    package: [50, 1],
    price: 169.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3048.png"
  },
  {  id: 3053,
    title: "Mammoth Smoke White",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Sky Pioneer",
    package: [36, 4],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 3058,
    title: "Monstrous Smoke Balls",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Topgun",
    package: [4, 12],
    price: 179.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 3061,
    title: "Jumbo Neon Smoke Ball",
    stock: true,
    category: "Snake & Smoke Items",
    brand: "Topgun",
    package: [72, 1],
    price: 229.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-3061.jpeg"
  },
  {  id: 4002,
    title: "Champagne Party Poppers (12/24/6)",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Sky Pioneer",
    package: [20, 12, 6],
    price: 189.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4009,
    title: "Hen Laying Eggs",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Sky Pioneer",
    package: [24, 24],
    price: 179.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4009.jpeg"
  },
  {  id: 4013,
    title: "Magnum Pistol Poppers",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Sky Pioneer",
    package: [20, 36],
    price: 169.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4014,
    title: "Pop Snappers",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Wise Guy",
    package: [6, 50, 50],
    price: 69.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4016,
    title: "Sky Lantern Assortment Colors",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Wise Guy",
    package: [6, 10],
    price: 199.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4016.png"
  },
  {  id: 4024,
    title: "Monster Pops",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Beihai PopPop",
    package: [10, 30, 20],
    price: 249.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4049,
    title: "Pagoda",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Sky Pioneer",
    package: [144, 1],
    price: 299.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4049.png"
  },
  {  id: 4051,
    title: "Poopie Doogal",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Topgun",
    package: [108, 2],
    price: 209.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4051.jpeg"
  },
  {  id: 4056,
    title: "Top Speed",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Topgun",
    package: [24, 1],
    price: 229.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4056.jpeg"
  },
  {  id: 4059,
    title: "Tanks Large",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Legend",
    package: [72, 2],
    price: 229.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4070,
    title: "Dragon W/ Wings",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Boom Wow",
    package: [72, 2],
    price: 189.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4070.png"
  },
  {  id: 4075,
    title: "Chariot Of Fire",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Sky Pioneer",
    package: [36, 1],
    price: 119.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4075.jpeg"
  },
  {  id: 4081,
    title: "Dinosaur's Return",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Sky Pioneer",
    package: [108, 2],
    price: 189.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-4081.jpeg"
  },
  {  id: 4106,
    title: "Ferris Wheel",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Sky Pioneer",
    package: [24, 1],
    price: 249.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4109,
    title: "Thunder King Snaps",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Miracle",
    package: [6, 24, 20],
    price: 139.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4114,
    title: "USA USA",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Miracle",
    package: [16, 1],
    price: 139.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4115,
    title: "Monster Truck",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Miracle",
    package: [24, 1],
    price: 169.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4118,
    title: "Spaceship",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Legend",
    package: [4, 12],
    price: 169.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4120,
    title: "Half Ton",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Brothers",
    package: [24, 1],
    price: 149.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4121,
    title: "Power Trip",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Brothers",
    package: [24, 1],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4122,
    title: "Spitfyre",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Brothers",
    package: [16, 1],
    price: 179.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4124,
    title: "Normandy Landing Craft",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Brothers",
    package: [54, 1],
    price: 349.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4125,
    title: "Ice Bird",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Brothers",
    package: [36, 2],
    price: 249.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 4132,
    title: "Ninja Disc",
    stock: true,
    category: "Toys, Novelties & Strobes",
    brand: "Miracle",
    package: [30, 2],
    price: 189.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 5000,
    title: "Fountain 9 Inch HN-90",
    stock: true,
    category: "Cone Shape & Floral Shells",
    brand: "Legend",
    package: [18, 4],
    price: 119.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-5000.jpeg"
  },
  {  id: 5001,
    title: "Crack Cone Cane",
    stock: true,
    category: "Cone Shape & Floral Shells",
    brand: "Legend",
    package: [18, 4],
    price: 159.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-5001.jpeg"
  },
  {  id: 5002,
    title: "Cuckoo Fountain",
    stock: true,
    category: "Cone Shape & Floral Shells",
    brand: "Legend",
    package: [24, 6],
    price: 139.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-5002.jpeg"
  },
  {  id: 5003,
    title: "Killer Bees",
    stock: true,
    category: "Cone Shape & Floral Shells",
    brand: "Legend",
    package: [24, 4],
    price: 109.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-5003.jpeg"
  },
  {  id: 5005,
    title: "Pyro Garden",
    stock: true,
    category: "Cone Shape & Floral Shells",
    brand: "Sky Pioneer",
    package: [24, 4],
    price: 179.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-5005.jpeg"
  },
  {  id: 5014,
    title: "God Of Fire",
    stock: true,
    category: "Cone Shape & Floral Shells",
    brand: "Black Scorpion",
    package: [10, 2],
    price: 179.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-5014.png"
  },
  {  id: 5018,
    title: "HN-89 Fountain/Happy Silver Flower",
    stock: true,
    category: "Cone Shape & Floral Shells",
    brand: "Sky Pioneer",
    package: [18, 4],
    price: 99.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: ""
  },
  {  id: 6006,
    title: "Sliders",
    stock: true,
    category: "Ground Items",
    brand: "Wise Guy",
    package: [6, 50, 10],
    price: 129.99,
    description: "This is an amazing assortment with top notch effects in every single fuse. Get a prepackaged assortment and get on with the show now.",
    image: "/product-imgs/pro-id-6006.jpeg"
  },
]